### ISSUE TITLE
Adding breadcrumbs to all resources.

### ISSUE THREAD

**Issue by philipbaginski** [Formfeed-UK/nova-breadcrumbs#1]
Hi!

It's not an issue, but I could not create request.

My question: Why we can not add breadcrumbs globally in Resource file, or Nova Service Provider file as a tool?

If we have plenty of resources and in any future this package will have any kind of not compatibility with any part of Nova, it will be very painful to remove code from all resources. Normally, commonly breadcrumbs are for all pages in the app, not only selected.

It is my point of view of course and fell free to give any kind of feedback to this question :-)

**Comment by ianrobertsFF** [comment]
It's built as a card because its the easiest way to add something to the top of all of the required pages.

Sure I could have wrapped the pages *again* in the style of my Resource Cards package and used a Tool or some such to add the Breadcrumbs to every page, but as I had already wrapped the pages for my resource cards this seemed like over-engineering. 

Theres nothing stopping you from overriding `resolveCards` on your `App/Nova/Resource.php` file which all of your Resources extend by default and doing the following:

```php
    public function resolveCards(NovaRequest $request)
    {
        array_unshift($this->cards($request), Breadcrumbs::make($request, $this));
        return collect(array_values($this->filter($this->cards($request))));
    }
```

**Comment by philipbaginski** [comment]
Thanx for comment. It makes sense. I will try to apply b. for all resources following your tip.

**Comment by philipbaginski** [comment]
:-) I had the same. Implementing breadcrumbs to one of the resource shows me the issue I was not going to discover with it. Thanks 🙏

**Comment by ianrobertsFF** [comment]
Awesome, closing this for now but if you need anything else feel free to open a new issue (or just reply here again if its related)
